discord:
  join:
    color: "#00ff00"
    message: "Игрок %player_name% присоединился к серверу!"
  first-time:
    color: "#0000ff"
    message: "Игрок %player_name% впервые на сервере!"
  leave:
    color: "#ff0000"
    message: "Игрок %player_name% покинул сервер!"
  url: ""
  icon: https://cravatar.eu/helmavatar/%player_name%/128.png
